### ISSUE TITLE
Not Found @xpack/xpm-liquid-ts@latest

### ISSUE THREAD

**Issue by Val-d-emar** [xpack/xpm-liquid-ts#6]
` npm install --save @xpack/xpm-liquid-ts@latest
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@xpack%2fxpm-liquid-ts - Not found
npm ERR! 404 
npm ERR! 404  '@xpack/xpm-liquid-ts@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-11-02T13_47_16_034Z-debug-0.log`

**Comment by ilg-ul** [comment]
Try `@xpack/xpm-liquid@latest`.
